FROM openkbs/jre-mvn-py3

USER root
WORKDIR /app/python-services

# Set up proxy
#ARG MY_PROXY_URL=http://proxy-grp1.lb-priv.sv2.247-inc.net:3128
#ENV HTTP_PROXY=$MY_PROXY_URL
#ENV HTTPS_PROXY=$MY_PROXY_URL
#ENV FTP_PROXY=$MY_PROXY_URL
#ENV http_proxy=$MY_PROXY_URL
#ENV https_proxy=$MY_PROXY_URL
#ENV ftp_proxy=$MY_PROXY_URL

ARG service=pyjenkins
ARG version=1.2
COPY requirements.txt .

#Install python packages
RUN pip install -r requirements.txt
ADD service ./service
ADD tests ./tests
COPY README.md setup.py setup.cfg .coveragerc logging.conf README.rst ./
COPY settings.xml ./
RUN mkdir -p /var/log/pyservices/

RUN coverage run -m pytest && coverage report && coverage xml